import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.scss";
import { Roboto } from "next/font/google";

import MainContainer from "@/components/layout/MainContainer";
import { SeasonProvider } from "@/_context/seasonsContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const gothic = Roboto({ subsets: ["latin-ext"], weight: ["400", "500", "700"] });

export const metadata: Metadata = {
  title: "Loveflix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${gothic.className} ${geistSans.className}`}>
        <SeasonProvider>
          <MainContainer>{children}</MainContainer>
        </SeasonProvider>
      </body>
    </html>
  );
}
